# a helper script to convert .ld files with human readable names of peripheral blocks' addresses to .h files with the same names.
# The .h files can then be used on a host to create memory commands (see memoryCommands.hpp) and thus move some initilization code 
# to a host 

print "// Generated by symbols.ld.to.addresses.h.pl from $ARGV[0]\n\n\n";

while (<>) { 
  if (/PROVIDE\((\w+)\s+=\s+([\da-fA-FXx]+)\);/) {
    print "#define $1 ($2)\n"
  } else { print }
}

